# These are the default parameters. They are read for all scenarios.
# Parameters will be overridden as needed for each scenario.

[MODEL]
# these determine how the model runs
# stop the model running at the first community infection?
IS_STOP_COMMUNITY_INFECTION = False
# stop farmers from returning home (to the community) if the farm has an infection on it
IS_QUARANTINE_FARMER = False

[TIME]
# total steps for 24-hour day
STEPS_PER_DAY = 24
# step numbers that are part of the working day - all VTH staff are at the hospital or farms, farmers are at farms
DAYTIME_STEPS = 8

[FARM VISITS]
# maximum number of farms that can be visited in a single trip from the VTH by a farm services clinician
MAX_VISITS_PER_TRIP = 3
# how long (steps) the clinician spends for a visit at a farm
VET_STEPS_AT_FARM = 1
# number of cows they see on the farm
VET_CONTACTS_PER_STEP = 10
# number of cows the truck comes into contact with
TRUCK_CONTACTS_PER_STEP = 10

# Note:
# 1. values apply across all farms, e.g. calls per day is sum of all calls from all the farms in the model
# 2. these are averages and there will be random variation in the model
EMERGENCY_VISITS_PER_MONTH = 3
# Unscheduled calls that aren't emergencies, should result in 1-2 visits per day in business hours
NON_URGENT_CALLS_PER_DAY = 2

# number of trucks the hospital has available for farm visits
NUM_TRUCKS = 3

# number of steps to travel between hospital and farm, or between farms
VISIT_TRAVEL_STEPS = 1

[DISEASE]
# the number of farms that have an infected cow at the start of the model
NUM_INIT_INFECTED_FARMS = 1

# infection probabilities given a contact
HUMAN_INFECT_CATTLE_PROB = 0.01
HUMAN_INFECT_HUMAN_PROB = 0.1
CATTLE_INFECT_HUMAN_PROB = 0.01
CATTLE_INFECT_CATTLE_PROB = 0.1

# number of days in the exposed, infectious, recovered states of the disease
HUMAN_EXPOSED_DAYS = 2
HUMAN_INFECTIOUS_DAYS = 10
HUMAN_RECOVERED_DAYS = 20

CATTLE_EXPOSED_DAYS = 2
CATTLE_INFECTED_DAYS = 10
CATTLE_RECOVERED_DAYS = 100

# probabilities of transfer of infectious material between truck and environment (farm or truck bay)
TRUCK_INFECT_ENV_PROB = 0.5
ENV_INFECT_TRUCK_PROB = 0.5

# disease interaction with environment
ENV_INFECT_HUMAN_PROB = 0.1
HUMAN_INFECT_ENV_PROB = 0.1
CATTLE_INFECT_ENV_PROB = 0.1
ENV_INFECT_CATTLE_PROB = 0.1

# time environment spends Infectious before reverting to Susceptible
ENV_INFECTIOUS_DAYS = 1


[COMMUNITY]
# define the community that's simulated in a compartmental model
# roughly the population of PEI
COMMUNITY_POPULATION = 200000
# average number of contacts per person per step (1 hour)
COMMUNITY_CONTACTS_PER_STEP = 1

[FARM]
# parameters to define the farms.
# Farms are simulated with compartmental models. Much of their behaviour is determined by the definitions in farms.xlsx
FREE_STALL_CONTACTS_PER_STEP = 10
TIE_STALL_CONTACTS_PER_STEP = 2
STRAW_PACK_CONTACTS_PER_STEP = 10
TIE_AND_STRAW_CONTACTS_PER_STEP = 5

# number of times milking occurs on a farm
NUM_MILKING_EVENTS_PER_DAY = 3

# number of contacts cow<->farmer at each milking event, including indirect contact through milking equipment
PARLOUR_MILKING_CONTACTS = 2
AMS_MILKING_CONTACTS = 2
PIPELINE_MILKING_CONTACTS = 2
ROTARY_PARLOUR_MILKING_CONTACTS = 2
