# These are the default parameters. They are read for all scenarios.
# Parameters will be overridden as needed for each scenario.

[MODEL]
# these determine how the model runs
# stop the model running at the first community infection?
IS_STOP_COMMUNITY_INFECTION = False
# stop farmers from returning home (to the community) if the farm has an infection on it
IS_QUARANTINE_FARM = False

[TIME]
# total steps for 24-hour day
STEPS_PER_DAY = 24
# step numbers that are part of the working day - all VTH staff are at the hospital or farms, farmers are at farms
DAYTIME_STEPS = 8

[FARM VISITS]
# maximum number of farms that can be visited in a single trip from the VTH by a farm services clinician
MAX_VISITS_PER_TRIP = 3
# how long (steps) the clinician spends for a visit at a farm
VET_STEPS_AT_FARM = 1
# number of cows they see on the farm
VET_CONTACTS_PER_STEP = 10

# Note:
# 1. values apply across all farms, e.g. calls per day is sum of all calls from all the farms in the model
# 2. these are averages and there will be random variation in the model
EMERGENCY_VISITS_PER_MONTH = 3
# Unscheduled calls that aren't emergencies
NON_URGENT_CALLS_PER_DAY = 2

# number of trucks the hospital has available for farm visits
NUM_TRUCKS = 3

# number of steps to travel between hospital and farm, or between farms
VISIT_TRAVEL_STEPS = 1

[DISEASE]
# the number of farms that have an infectious cow at the start of the model
NUM_INIT_INFECTED_FARMS = 1

# infection probabilities given a contact
HUMAN_INFECT_CATTLE_PROB = 0.001
HUMAN_INFECT_HUMAN_PROB = 0.1
CATTLE_INFECT_HUMAN_PROB = 0.001
CATTLE_INFECT_CATTLE_PROB = 0.1

# probabilities of transfer of infectious material between truck and environment (farm or truck bay)
TRUCK_INFECT_ENV_PROB = 0.3
ENV_INFECT_TRUCK_PROB = 0.3

# disease interaction with environment
ENV_INFECT_HUMAN_PROB = 0.01
HUMAN_INFECT_ENV_PROB = 0.01
CATTLE_INFECT_ENV_PROB = 0.01
ENV_INFECT_CATTLE_PROB = 0.01

# vaccination reduces the probabilities of both being infected and infecting. Only people/humans are vaccinated
# VACC_ROLES is either None or a comma (,) separated list of the roles of people that are getting vaccinated
# possible roles are: farmer, farm services vet, farm services technician, farm services student, large animal vet,
# large animal staff, large animal student, small animal vet, small animal staff, small animal student, floating vet,
# floating clinician, floating staff, floating student
VACC_ROLES = None
VACC_HUMAN_INFECT_CATTLE_PROB = 0.0001
VACC_CATTLE_INFECT_HUMAN_PROB = 0.0001
VACC_HUMAN_INFECT_HUMAN_PROB = 0.01
VACC_HUMAN_INFECT_ENV_PROB = 0.001
VACC_ENV_INFECT_HUMAN_PROB = 0.001

# number of days in the exposed, infectious, recovered states of the disease
HUMAN_EXPOSED_DAYS = 2
HUMAN_INFECTIOUS_DAYS = 10
HUMAN_RECOVERED_DAYS = 20

# days since exposed until showing symptoms and diagnosed
HUMAN_SYMPTOMATIC_DAYS = 7

CATTLE_EXPOSED_DAYS = 2
CATTLE_INFECTED_DAYS = 10
CATTLE_RECOVERED_DAYS = 100

# days environment spends Infectious before reverting to Susceptible
ENV_INFECTIOUS_DAYS = 1

[COMMUNITY]
# define the community that's simulated in a compartmental model
# roughly the population of PEI
COMMUNITY_POPULATION = 200000
# average number of contacts per person per step (1 hour)
COMMUNITY_CONTACTS_PER_STEP = 1

[FARM]
# parameters to define the farms.
# Farms are simulated with compartmental models. Much of their behaviour is determined by the definitions in farms.xlsx
FREE_STALL_CONTACTS_PER_STEP = 10
TIE_STALL_CONTACTS_PER_STEP = 2
STRAW_PACK_CONTACTS_PER_STEP = 10
TIE_AND_STRAW_CONTACTS_PER_STEP = 5

# number of times milking occurs on a farm
NUM_MILKING_EVENTS_PER_DAY = 3

# number of contacts cow<->farmer at each milking event, including indirect contact through milking equipment
PARLOUR_MILKING_CONTACTS = 2
AMS_MILKING_CONTACTS = 2
PIPELINE_MILKING_CONTACTS = 2
ROTARY_PARLOUR_MILKING_CONTACTS = 2

[CLEANING]
# cleaning removes infection from a location agent

# none: truck isn't cleaned
# daily: at the end of each day
# visit: after returning to the hospital after each visit to farms
TRUCK = None

# none: hospital areas aren't cleaned (enough to remove this infectious material)
# daily: cleaned at the end of each day
HOSPITAL = None

[PEOPLE]
# the name of the sheet in people.xlsx to use to define the hospital people
SHEET_NAME = default
